runner:

  cppcheck:
    cmd: cppcheck --enable=all --template="{file}:{line}:{message}" src/
    errorformat:
      - "%f:%l:%m"
    level: warning

  luacheck:
    cmd: luacheck --formatter=plain --no-color --no-config --no-global --no-unused --no-unused-args --no-cache -d ./data/
    errorformat:
      - "%f:%l:%c: %m"
    level: warning

  xmllint:
    cmd: find data/ -name '*.xml' -print0 | xargs -0 -n1 xmllint --noout
    errorformat:
      - "%f:%l:%c: %m"
    level: warning
