name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - develop
      - v*

    tags:
      - v*

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - .github/**

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        buildtype: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: >
        sudo apt-get update && sudo apt-get install cmake build-essential
        liblua5.2-dev libmysqlclient-dev libboost-system-dev
        libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev
        libboost-date-time-dev libgmp-dev zip

    - name: Prepare build Environment
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} ..

    - name: Build
      run: |
        cd build
        make -j `nproc`
        mv bin/canary ../

    - name: Clean workspace
      shell: bash
      run: find . -maxdepth 1 ! -name data ! -name config.lua.dist ! -name LICENSE ! -name canary ! -name README.md ! -name schema.sql -exec rm -r {} \;

    - name: Prepare datapack contents
      shell: bash
      run: |
        mv config.lua.dist config.lua
        cd ..
        zip -r canary.zip canary-server

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: canary-${{ matrix.os }}-amd64-${{ matrix.buildtype }}-${{ github.sha }}
        path: ${{ runner.workspace }}/canary.zip
